#!/bin/bash

echo "" > mmlog.txt

./m.sh traverser_1 blt_funcs 2>> mmlog.txt
./m.sh traverser_1 scope_0 2>> mmlog.txt
./m.sh traverser_1 scope_1 2>> mmlog.txt
./m.sh traverser_1 scope_2 2>> mmlog.txt
./m.sh traverser_1 scope_3 2>> mmlog.txt
./m.sh traverser_1 scope_4 2>> mmlog.txt
./m.sh traverser_1 scope_5 2>> mmlog.txt
./m.sh traverser_1 scope_6 2>> mmlog.txt
./m.sh traverser_1 scope_7 2>> mmlog.txt
./m.sh traverser_1 mutable_and_immutable 2>> mmlog.txt
./m.sh traverser_1 assign_and_reference_0 2>> mmlog.txt
./m.sh traverser_1 assign_and_reference_1 2>> mmlog.txt
./m.sh traverser_1 assign_and_reference_2 2>> mmlog.txt
./m.sh traverser_1 assign_and_reference_3 2>> mmlog.txt
./m.sh traverser_1 assign_and_reference_4 2>> mmlog.txt
./m.sh traverser_1 assign_and_reference_5 2>> mmlog.txt
./m.sh traverser_1 assign_and_reference_6 2>> mmlog.txt
./m.sh traverser_1 assign_and_reference_7 2>> mmlog.txt
./m.sh traverser_1 assign_and_reference_8 2>> mmlog.txt
./m.sh traverser_1 assign_and_reference_9 2>> mmlog.txt
./m.sh traverser_1 assign_and_reference_10 2>> mmlog.txt
./m.sh traverser_1 assign_and_reference_11 2>> mmlog.txt
./m.sh traverser_1 assign_and_reference_11_5 2>> mmlog.txt
./m.sh traverser_1 assign_and_reference_11_6 2>> mmlog.txt
./m.sh traverser_1 assign_and_reference_11_7 2>> mmlog.txt
./m.sh traverser_1 assign_and_reference_12 2>> mmlog.txt
./m.sh traverser_1 assign_and_reference_13 2>> mmlog.txt
./m.sh traverser_1 assign_and_reference_14 2>> mmlog.txt
./m.sh traverser_1 assign_and_reference_15 2>> mmlog.txt
./m.sh traverser_1 assign_and_reference_16 2>> mmlog.txt
./m.sh traverser_1 assign_and_reference_all 2>> mmlog.txt
./m.sh traverser_1 code_block 2>> mmlog.txt
./m.sh traverser_1 code_block_fail 2>> mmlog.txt
./m.sh traverser_1 ref_block 2>> mmlog.txt
./m.sh traverser_1 ref_block_fail 2>> mmlog.txt
./m.sh traverser_1 text_block 2>> mmlog.txt
./m.sh traverser_1 type_0 2>> mmlog.txt
./m.sh traverser_1 type_1 2>> mmlog.txt
./m.sh traverser_1 type_2 2>> mmlog.txt
./m.sh traverser_1 type_3 2>> mmlog.txt
./m.sh traverser_1 type_4 2>> mmlog.txt
./m.sh traverser_1 type_5 2>> mmlog.txt
./m.sh traverser_1 assign_list_0 2>> mmlog.txt
./m.sh traverser_1 assign_list_1 2>> mmlog.txt
./m.sh traverser_1 assign_list_2 2>> mmlog.txt
./m.sh traverser_1 assign_list_3 2>> mmlog.txt
./m.sh traverser_1 assign_list_fail_0 2>> mmlog.txt
./m.sh traverser_1 multi_assign_0 2>> mmlog.txt
./m.sh traverser_1 multi_assign_1 2>> mmlog.txt
./m.sh traverser_1 multi_assign_2 2>> mmlog.txt
./m.sh traverser_1 multi_assign_fail_0 2>> mmlog.txt
./m.sh traverser_1 or_test_0 2>> mmlog.txt
./m.sh traverser_1 or_test_fail_0 2>> mmlog.txt
./m.sh traverser_1 and_test_0 2>> mmlog.txt
./m.sh traverser_1 and_test_fail_0 2>> mmlog.txt
./m.sh traverser_1 not_test_0 2>> mmlog.txt
./m.sh traverser_1 not_test_fail_0 2>> mmlog.txt
./m.sh traverser_1 asscalc_0 2>> mmlog.txt
./m.sh traverser_1 asscalc_1 2>> mmlog.txt
./m.sh traverser_1 asscalc_2 2>> mmlog.txt
./m.sh traverser_1 asscalc_3 2>> mmlog.txt
./m.sh traverser_1 asscalc_4 2>> mmlog.txt
./m.sh traverser_1 asscalc_5 2>> mmlog.txt
./m.sh traverser_1 asscalc_6 2>> mmlog.txt
./m.sh traverser_1 asscalc_7 2>> mmlog.txt
./m.sh traverser_1 asscalc_8 2>> mmlog.txt
./m.sh traverser_1 asscalc_9 2>> mmlog.txt
./m.sh traverser_1 asscalc_10 2>> mmlog.txt
./m.sh traverser_1 asscalc_11 2>> mmlog.txt
./m.sh traverser_1 asscalc_12 2>> mmlog.txt
./m.sh traverser_1 asscalc_13 2>> mmlog.txt
./m.sh traverser_1 asscalc_14 2>> mmlog.txt
./m.sh traverser_1 asscalc_15 2>> mmlog.txt
./m.sh traverser_1 asscalc_16 2>> mmlog.txt
./m.sh traverser_1 asscalc_17 2>> mmlog.txt
./m.sh traverser_1 asscalc_18 2>> mmlog.txt
./m.sh traverser_1 asscalc_19 2>> mmlog.txt
./m.sh traverser_1 asscalc_20 2>> mmlog.txt
./m.sh traverser_1 asscalc_21 2>> mmlog.txt
./m.sh traverser_1 asscalc_22 2>> mmlog.txt
./m.sh traverser_1 asscalc_23 2>> mmlog.txt
./m.sh traverser_1 asscalc_24 2>> mmlog.txt
./m.sh traverser_1 asscalc_25 2>> mmlog.txt
./m.sh traverser_1 asscalc_add_ass_string 2>> mmlog.txt
./m.sh traverser_1 asscalc_fail_0 2>> mmlog.txt
./m.sh traverser_1 expr_0 2>> mmlog.txt
./m.sh traverser_1 expr_1 2>> mmlog.txt
./m.sh traverser_1 expr_2 2>> mmlog.txt
./m.sh traverser_1 expr_3 2>> mmlog.txt
./m.sh traverser_1 expr_4 2>> mmlog.txt
./m.sh traverser_1 expr_4a 2>> mmlog.txt
./m.sh traverser_1 expr_5 2>> mmlog.txt
./m.sh traverser_1 expr_6 2>> mmlog.txt
./m.sh traverser_1 expr_7 2>> mmlog.txt
./m.sh traverser_1 expr_8 2>> mmlog.txt
./m.sh traverser_1 expr_9 2>> mmlog.txt
./m.sh traverser_1 expr_float 2>> mmlog.txt
./m.sh traverser_1 expr_string_0 2>> mmlog.txt
./m.sh traverser_1 expr_fail_0 2>> mmlog.txt
./m.sh traverser_1 term_0 2>> mmlog.txt
./m.sh traverser_1 term_1 2>> mmlog.txt
./m.sh traverser_1 term_2 2>> mmlog.txt
./m.sh traverser_1 term_3 2>> mmlog.txt
./m.sh traverser_1 term_fail_0 2>> mmlog.txt
./m.sh traverser_1 call_0 2>> mmlog.txt
./m.sh traverser_1 call_1 2>> mmlog.txt
./m.sh traverser_1 call_2 2>> mmlog.txt
./m.sh traverser_1 call_3 2>> mmlog.txt
./m.sh traverser_1 call_4 2>> mmlog.txt
./m.sh traverser_1 call_5 2>> mmlog.txt
./m.sh traverser_1 call_fail_0 2>> mmlog.txt
./m.sh traverser_1 call_fail_1 2>> mmlog.txt
./m.sh traverser_1 call_fail_2 2>> mmlog.txt
./m.sh traverser_1 call_fail_3 2>> mmlog.txt
./m.sh traverser_1 call_fail_4 2>> mmlog.txt
./m.sh traverser_1 index_0 2>> mmlog.txt
./m.sh traverser_1 index_1 2>> mmlog.txt
./m.sh traverser_1 index_fail_0 2>> mmlog.txt

./m.sh traverser_2 vec_0 2>> mmlog.txt
./m.sh traverser_2 vec_1 2>> mmlog.txt
./m.sh traverser_2 vec_2 2>> mmlog.txt
./m.sh traverser_2 vec_3 2>> mmlog.txt
./m.sh traverser_2 vec_4 2>> mmlog.txt
./m.sh traverser_2 vec_5 2>> mmlog.txt
./m.sh traverser_2 vec_6 2>> mmlog.txt
./m.sh traverser_2 vec_7 2>> mmlog.txt
./m.sh traverser_2 vec_8 2>> mmlog.txt
./m.sh traverser_2 vec_9 2>> mmlog.txt
./m.sh traverser_2 vec_10 2>> mmlog.txt
./m.sh traverser_2 vec_11 2>> mmlog.txt
./m.sh traverser_2 vec_12 2>> mmlog.txt
./m.sh traverser_2 vec_13 2>> mmlog.txt
./m.sh traverser_2 vec_fail_0 2>> mmlog.txt
./m.sh traverser_2 nil 2>> mmlog.txt
./m.sh traverser_2 false 2>> mmlog.txt
./m.sh traverser_2 true 2>> mmlog.txt
./m.sh traverser_2 digit 2>> mmlog.txt
./m.sh traverser_2 string 2>> mmlog.txt
./m.sh traverser_2 dict_0 2>> mmlog.txt
./m.sh traverser_2 dict_1 2>> mmlog.txt
./m.sh traverser_2 dict_2 2>> mmlog.txt
./m.sh traverser_2 dict_3 2>> mmlog.txt
./m.sh traverser_2 dict_4 2>> mmlog.txt
./m.sh traverser_2 dict_5 2>> mmlog.txt
./m.sh traverser_2 dict_fail_0 2>> mmlog.txt
./m.sh traverser_2 identifier 2>> mmlog.txt
./m.sh traverser_2 traverse 2>> mmlog.txt
./m.sh traverser_2 long_code 2>> mmlog.txt
./m.sh traverser_2 comparison 2>> mmlog.txt
./m.sh traverser_2 comparison_0 2>> mmlog.txt
./m.sh traverser_2 comparison_1 2>> mmlog.txt
./m.sh traverser_2 comparison_2 2>> mmlog.txt
./m.sh traverser_2 comparison_3 2>> mmlog.txt
./m.sh traverser_2 comparison_4 2>> mmlog.txt
./m.sh traverser_2 comparison_5 2>> mmlog.txt
./m.sh traverser_2 comparison_6 2>> mmlog.txt
./m.sh traverser_2 comparison_7 2>> mmlog.txt
./m.sh traverser_2 vec_index 2>> mmlog.txt
./m.sh traverser_2 text_block_old 2>> mmlog.txt
./m.sh traverser_2 ref_block_old 2>> mmlog.txt
./m.sh traverser_2 assign_0 2>> mmlog.txt
./m.sh traverser_2 assign_1 2>> mmlog.txt
./m.sh traverser_2 assign_2 2>> mmlog.txt
./m.sh traverser_2 assign_3 2>> mmlog.txt
./m.sh traverser_2 assign_4 2>> mmlog.txt
./m.sh traverser_2 assign_5 2>> mmlog.txt
./m.sh traverser_2 assign_fail_0 2>> mmlog.txt
./m.sh traverser_2 atom_0 2>> mmlog.txt
./m.sh traverser_2 index 2>> mmlog.txt
./m.sh traverser_2 string_index 2>> mmlog.txt
./m.sh traverser_2 multi_assign 2>> mmlog.txt
./m.sh traverser_2 and_test 2>> mmlog.txt
./m.sh traverser_2 assign_list 2>> mmlog.txt
./m.sh traverser_2 test_list 2>> mmlog.txt
./m.sh traverser_2 dot_0 2>> mmlog.txt
./m.sh traverser_2 dot_1 2>> mmlog.txt
./m.sh traverser_2 dot_2 2>> mmlog.txt
./m.sh traverser_2 dot_3 2>> mmlog.txt
./m.sh traverser_2 dot_4 2>> mmlog.txt
./m.sh traverser_2 dot_5 2>> mmlog.txt
./m.sh traverser_2 dot_6 2>> mmlog.txt
./m.sh traverser_2 negative_0 2>> mmlog.txt
./m.sh traverser_2 call 2>> mmlog.txt
./m.sh traverser_2 module_0 2>> mmlog.txt
./m.sh traverser_2 chain_object 2>> mmlog.txt
./m.sh traverser_2 etc_0 2>> mmlog.txt
./m.sh traverser_2 etc_1 2>> mmlog.txt
./m.sh traverser_2 etc_2 2>> mmlog.txt
./m.sh traverser_2 etc_3 2>> mmlog.txt
./m.sh traverser_2 etc_4 2>> mmlog.txt
./m.sh traverser_2 etc_5 2>> mmlog.txt
./m.sh traverser_2 etc_6 2>> mmlog.txt
./m.sh traverser_2 etc_7 2>> mmlog.txt
./m.sh traverser_2 etc_8 2>> mmlog.txt
./m.sh traverser_2 etc_9 2>> mmlog.txt
./m.sh traverser_2 etc_10 2>> mmlog.txt
./m.sh traverser_2 unicode_0 2>> mmlog.txt
./m.sh traverser_2 unicode_1 2>> mmlog.txt
./m.sh traverser_2 import_stmt_0 2>> mmlog.txt
./m.sh traverser_2 import_stmt_1 2>> mmlog.txt
./m.sh traverser_2 import_stmt_2 2>> mmlog.txt
./m.sh traverser_2 import_stmt_3 2>> mmlog.txt
./m.sh traverser_2 import_stmt_4 2>> mmlog.txt
./m.sh traverser_2 import_stmt_5 2>> mmlog.txt
./m.sh traverser_2 from_import_stmt_1 2>> mmlog.txt
./m.sh traverser_2 from_import_stmt_2 2>> mmlog.txt
./m.sh traverser_2 from_import_stmt_3 2>> mmlog.txt

./m.sh traverser_3 if_stmt_0 2>> mmlog.txt
./m.sh traverser_3 if_stmt_1 2>> mmlog.txt
./m.sh traverser_3 if_stmt_2 2>> mmlog.txt
./m.sh traverser_3 if_stmt_3 2>> mmlog.txt
./m.sh traverser_3 if_stmt_4 2>> mmlog.txt
./m.sh traverser_3 if_stmt_5 2>> mmlog.txt
./m.sh traverser_3 if_stmt_6 2>> mmlog.txt
./m.sh traverser_3 if_stmt_7 2>> mmlog.txt
./m.sh traverser_3 if_stmt_8 2>> mmlog.txt
./m.sh traverser_3 if_stmt_9 2>> mmlog.txt
./m.sh traverser_3 if_stmt_10 2>> mmlog.txt
./m.sh traverser_3 if_stmt_11 2>> mmlog.txt
./m.sh traverser_3 if_stmt_12 2>> mmlog.txt
./m.sh traverser_3 if_stmt_13 2>> mmlog.txt
./m.sh traverser_3 if_stmt_fail_0 2>> mmlog.txt
./m.sh traverser_3 if_stmt_fail_1 2>> mmlog.txt
./m.sh traverser_3 elif_stmt_0 2>> mmlog.txt
./m.sh traverser_3 elif_stmt_1 2>> mmlog.txt
./m.sh traverser_3 elif_stmt_2 2>> mmlog.txt
./m.sh traverser_3 elif_stmt_3 2>> mmlog.txt
./m.sh traverser_3 elif_stmt_4 2>> mmlog.txt
./m.sh traverser_3 elif_stmt_5 2>> mmlog.txt
./m.sh traverser_3 elif_stmt_6 2>> mmlog.txt
./m.sh traverser_3 elif_stmt_7 2>> mmlog.txt
./m.sh traverser_3 else_stmt_0 2>> mmlog.txt
./m.sh traverser_3 else_stmt_1 2>> mmlog.txt
./m.sh traverser_3 else_stmt_2 2>> mmlog.txt
./m.sh traverser_3 else_stmt_3 2>> mmlog.txt
./m.sh traverser_3 else_stmt_4 2>> mmlog.txt
./m.sh traverser_3 for_stmt_0 2>> mmlog.txt
./m.sh traverser_3 for_stmt_1 2>> mmlog.txt
./m.sh traverser_3 for_stmt_2 2>> mmlog.txt
./m.sh traverser_3 for_stmt_3 2>> mmlog.txt
./m.sh traverser_3 for_stmt_4 2>> mmlog.txt
./m.sh traverser_3 for_stmt_5 2>> mmlog.txt
./m.sh traverser_3 for_stmt_6 2>> mmlog.txt
./m.sh traverser_3 for_stmt_7 2>> mmlog.txt
./m.sh traverser_3 for_stmt_8 2>> mmlog.txt
./m.sh traverser_3 for_stmt_9 2>> mmlog.txt
./m.sh traverser_3 for_stmt_10 2>> mmlog.txt
./m.sh traverser_3 for_stmt_11 2>> mmlog.txt
./m.sh traverser_3 for_stmt_12 2>> mmlog.txt
./m.sh traverser_3 break_stmt_0 2>> mmlog.txt
./m.sh traverser_3 break_stmt_1 2>> mmlog.txt
./m.sh traverser_3 break_stmt_2 2>> mmlog.txt
./m.sh traverser_3 break_stmt_3 2>> mmlog.txt
./m.sh traverser_3 continue_stmt_0 2>> mmlog.txt
./m.sh traverser_3 continue_stmt_1 2>> mmlog.txt
./m.sh traverser_3 continue_stmt_2 2>> mmlog.txt
./m.sh traverser_3 continue_stmt_3 2>> mmlog.txt
./m.sh traverser_3 continue_stmt_4 2>> mmlog.txt
./m.sh traverser_3 continue_stmt_5 2>> mmlog.txt
./m.sh traverser_3 return_stmt_0 2>> mmlog.txt
./m.sh traverser_3 return_stmt_1 2>> mmlog.txt
./m.sh traverser_3 return_stmt_2 2>> mmlog.txt
./m.sh traverser_3 return_stmt_3 2>> mmlog.txt
./m.sh traverser_3 return_stmt_4 2>> mmlog.txt
./m.sh traverser_3 return_stmt_5 2>> mmlog.txt
./m.sh traverser_3 return_stmt_6 2>> mmlog.txt
./m.sh traverser_3 block_stmt_0 2>> mmlog.txt
./m.sh traverser_3 block_stmt_1 2>> mmlog.txt
./m.sh traverser_3 block_stmt_2 2>> mmlog.txt
./m.sh traverser_3 block_stmt_3 2>> mmlog.txt
./m.sh traverser_3 block_stmt_4 2>> mmlog.txt
./m.sh traverser_3 block_stmt_fail_0 2>> mmlog.txt
./m.sh traverser_3 inject_stmt_0 2>> mmlog.txt
./m.sh traverser_3 inject_stmt_1 2>> mmlog.txt
./m.sh traverser_3 inject_stmt_2 2>> mmlog.txt
./m.sh traverser_3 inject_stmt_3 2>> mmlog.txt
./m.sh traverser_3 inject_stmt_4 2>> mmlog.txt
./m.sh traverser_3 inject_stmt_5 2>> mmlog.txt
./m.sh traverser_3 inject_stmt_6 2>> mmlog.txt
./m.sh traverser_3 inject_stmt_7 2>> mmlog.txt
./m.sh traverser_3 inject_stmt_8 2>> mmlog.txt
./m.sh traverser_3 inject_stmt_9 2>> mmlog.txt
./m.sh traverser_3 inject_stmt_10 2>> mmlog.txt
./m.sh traverser_3 inject_stmt_11 2>> mmlog.txt
./m.sh traverser_3 inject_stmt_12 2>> mmlog.txt
./m.sh traverser_3 inject_stmt_13 2>> mmlog.txt
./m.sh traverser_3 inject_stmt_14 2>> mmlog.txt
./m.sh traverser_3 inject_stmt_15 2>> mmlog.txt
./m.sh traverser_3 inject_stmt_16 2>> mmlog.txt
./m.sh traverser_3 inject_stmt_17 2>> mmlog.txt
./m.sh traverser_3 inject_stmt_18 2>> mmlog.txt
./m.sh traverser_3 inject_stmt_19 2>> mmlog.txt
./m.sh traverser_3 inject_stmt_20 2>> mmlog.txt
./m.sh traverser_3 inject_stmt_21 2>> mmlog.txt
./m.sh traverser_3 inject_stmt_fail_0 2>> mmlog.txt
./m.sh traverser_3 func_def_0 2>> mmlog.txt
./m.sh traverser_3 func_def_1 2>> mmlog.txt
./m.sh traverser_3 func_def_2 2>> mmlog.txt
./m.sh traverser_3 func_def_3 2>> mmlog.txt
./m.sh traverser_3 func_def_4 2>> mmlog.txt
./m.sh traverser_3 func_def_5 2>> mmlog.txt
./m.sh traverser_3 func_def_6 2>> mmlog.txt
./m.sh traverser_3 func_def_7 2>> mmlog.txt
./m.sh traverser_3 func_def_8 2>> mmlog.txt
./m.sh traverser_3 func_def_9 2>> mmlog.txt
./m.sh traverser_3 func_def_10 2>> mmlog.txt
./m.sh traverser_3 func_def_11 2>> mmlog.txt
./m.sh traverser_3 func_def_12 2>> mmlog.txt
./m.sh traverser_3 func_def_13 2>> mmlog.txt
./m.sh traverser_3 func_def_14 2>> mmlog.txt
./m.sh traverser_3 func_def_fail_0 2>> mmlog.txt
./m.sh traverser_3 func_met_0 2>> mmlog.txt
./m.sh traverser_3 func_met_1 2>> mmlog.txt
./m.sh traverser_3 func_met_1_2 2>> mmlog.txt
./m.sh traverser_3 func_met_2 2>> mmlog.txt
./m.sh traverser_3 func_met_3 2>> mmlog.txt
./m.sh traverser_3 func_met_4 2>> mmlog.txt
./m.sh traverser_3 func_met_5 2>> mmlog.txt
./m.sh traverser_3 func_extends_0 2>> mmlog.txt
./m.sh traverser_3 func_extends_fail_0 2>> mmlog.txt
./m.sh traverser_3 func_super_0 2>> mmlog.txt
./m.sh traverser_3 func_super_1 2>> mmlog.txt
./m.sh traverser_3 func_super_2 2>> mmlog.txt
./m.sh traverser_3 func_super_fail_0 2>> mmlog.txt
./m.sh traverser_3 struct_1 2>> mmlog.txt
./m.sh traverser_3 struct_2 2>> mmlog.txt
./m.sh traverser_3 struct_3 2>> mmlog.txt
./m.sh traverser_3 struct_4 2>> mmlog.txt
./m.sh traverser_3 struct_5 2>> mmlog.txt
./m.sh traverser_3 struct_6 2>> mmlog.txt
./m.sh traverser_3 struct_7 2>> mmlog.txt
./m.sh traverser_3 struct_8 2>> mmlog.txt
./m.sh traverser_3 struct_9 2>> mmlog.txt
./m.sh traverser_3 struct_10 2>> mmlog.txt
./m.sh traverser_3 struct_11 2>> mmlog.txt
./m.sh traverser_3 struct_12 2>> mmlog.txt
./m.sh traverser_3 struct_13 2>> mmlog.txt
./m.sh traverser_3 struct_14 2>> mmlog.txt
./m.sh traverser_3 struct_15 2>> mmlog.txt
./m.sh traverser_3 struct_16 2>> mmlog.txt
./m.sh traverser_3 struct_17 2>> mmlog.txt
./m.sh traverser_3 struct_17_2 2>> mmlog.txt
./m.sh traverser_3 struct_17_3 2>> mmlog.txt
./m.sh traverser_3 struct_18 2>> mmlog.txt
./m.sh traverser_3 struct_19 2>> mmlog.txt
./m.sh traverser_3 struct_20 2>> mmlog.txt
./m.sh traverser_3 struct_21 2>> mmlog.txt
./m.sh traverser_3 struct_22 2>> mmlog.txt
./m.sh traverser_3 struct_23 2>> mmlog.txt
./m.sh traverser_3 struct_24 2>> mmlog.txt
./m.sh traverser_3 struct_25 2>> mmlog.txt
./m.sh traverser_3 struct_26 2>> mmlog.txt
./m.sh traverser_3 struct_27 2>> mmlog.txt
./m.sh traverser_3 struct_28 2>> mmlog.txt
./m.sh traverser_3 struct_29 2>> mmlog.txt
./m.sh traverser_3 struct_30 2>> mmlog.txt
./m.sh traverser_3 struct_31 2>> mmlog.txt
./m.sh traverser_3 struct_32 2>> mmlog.txt
./m.sh traverser_3 struct_33 2>> mmlog.txt
./m.sh traverser_3 struct_34 2>> mmlog.txt
./m.sh traverser_3 struct_35 2>> mmlog.txt
./m.sh traverser_3 struct_36 2>> mmlog.txt
./m.sh traverser_3 struct_37 2>> mmlog.txt
./m.sh traverser_3 struct_38 2>> mmlog.txt
./m.sh traverser_3 struct_39 2>> mmlog.txt
./m.sh traverser_3 struct_40 2>> mmlog.txt
./m.sh traverser_3 struct_41 2>> mmlog.txt
./m.sh traverser_3 struct_42 2>> mmlog.txt
./m.sh traverser_3 struct_43 2>> mmlog.txt
./m.sh traverser_3 struct_44 2>> mmlog.txt
./m.sh traverser_3 struct_45 2>> mmlog.txt
./m.sh traverser_3 struct_46 2>> mmlog.txt
./m.sh traverser_3 struct_47 2>> mmlog.txt
./m.sh traverser_3 struct_48 2>> mmlog.txt
./m.sh traverser_3 struct_49 2>> mmlog.txt
./m.sh traverser_3 struct_50 2>> mmlog.txt
./m.sh traverser_3 struct_51 2>> mmlog.txt
./m.sh traverser_3 struct_52 2>> mmlog.txt
./m.sh traverser_3 struct_53 2>> mmlog.txt
./m.sh traverser_3 struct_54 2>> mmlog.txt
./m.sh traverser_3 struct_55 2>> mmlog.txt
./m.sh traverser_3 struct_56 2>> mmlog.txt
./m.sh traverser_3 struct_57 2>> mmlog.txt
./m.sh traverser_3 struct_58 2>> mmlog.txt
./m.sh traverser_3 struct_59 2>> mmlog.txt
./m.sh traverser_3 struct_60 2>> mmlog.txt
./m.sh traverser_3 struct_fail_0 2>> mmlog.txt
./m.sh traverser_3 builtin_modules_opts_0 2>> mmlog.txt
./m.sh traverser_3 builtin_modules_alias_0 2>> mmlog.txt
./m.sh traverser_3 builtin_modules_alias_1 2>> mmlog.txt
./m.sh traverser_3 builtin_modules_alias_2 2>> mmlog.txt
./m.sh traverser_3 builtin_modules_vec_0 2>> mmlog.txt
./m.sh traverser_3 builtin_modules_vec_1 2>> mmlog.txt
./m.sh traverser_3 builtin_functions 2>> mmlog.txt
./m.sh traverser_3 builtin_functions_puts_0 2>> mmlog.txt
./m.sh traverser_3 builtin_functions_len_0 2>> mmlog.txt
./m.sh traverser_3 builtin_functions_type 2>> mmlog.txt
./m.sh traverser_3 builtin_functions_cast 2>> mmlog.txt
./m.sh traverser_3 builtin_functions_type_dict 2>> mmlog.txt
./m.sh traverser_3 builtin_functions_copy_0 2>> mmlog.txt
./m.sh traverser_3 builtin_functions_deepcopy_0 2>> mmlog.txt
./m.sh traverser_3 builtin_functions_assert_0 2>> mmlog.txt
./m.sh traverser_3 builtin_functions_assert_1 2>> mmlog.txt
./m.sh traverser_3 builtin_functions_extract_0 2>> mmlog.txt
./m.sh traverser_3 builtin_functions_setattr_0 2>> mmlog.txt
./m.sh traverser_3 builtin_functions_getattr_0 2>> mmlog.txt
./m.sh traverser_3 builtin_functions_dance_0 2>> mmlog.txt
./m.sh traverser_3 builtin_functions_ord_0 2>> mmlog.txt
./m.sh traverser_3 builtin_functions_chr_0 2>> mmlog.txt
./m.sh traverser_3 builtin_string 2>> mmlog.txt
./m.sh traverser_3 builtin_unicode_split 2>> mmlog.txt
./m.sh traverser_3 builtin_unicode_rstrip 2>> mmlog.txt
./m.sh traverser_3 builtin_unicode_lstrip 2>> mmlog.txt
./m.sh traverser_3 builtin_unicode_strip 2>> mmlog.txt
./m.sh traverser_3 builtin_unicode_isdigit 2>> mmlog.txt
./m.sh traverser_3 builtin_unicode_isalpha 2>> mmlog.txt
./m.sh traverser_3 builtin_unicode_isspace 2>> mmlog.txt
./m.sh traverser_3 builtin_vec_0 2>> mmlog.txt
./m.sh traverser_3 builtin_dict_0 2>> mmlog.txt
./m.sh traverser_3 builtin_open_0 2>> mmlog.txt
./m.sh traverser_4 try_catch_stmt_1 2>> mmlog.txt
./m.sh traverser_4 try_catch_stmt_2 2>> mmlog.txt
./m.sh traverser_4 try_catch_stmt_3 2>> mmlog.txt
./m.sh traverser_4 try_catch_stmt_4 2>> mmlog.txt
./m.sh traverser_4 try_catch_stmt_5 2>> mmlog.txt
./m.sh traverser_4 try_catch_stmt_6 2>> mmlog.txt
./m.sh traverser_4 try_catch_stmt_7 2>> mmlog.txt
./m.sh traverser_4 try_catch_stmt_8 2>> mmlog.txt
./m.sh traverser_4 try_catch_stmt_9 2>> mmlog.txt
./m.sh traverser_4 try_catch_stmt_10 2>> mmlog.txt
./m.sh traverser_4 try_catch_stmt_11 2>> mmlog.txt
./m.sh traverser_4 try_catch_stmt_12 2>> mmlog.txt
./m.sh traverser_4 try_catch_stmt_13 2>> mmlog.txt
./m.sh traverser_4 try_catch_stmt_14 2>> mmlog.txt
./m.sh traverser_4 try_catch_stmt_15 2>> mmlog.txt
./m.sh traverser_4 try_catch_stmt_16 2>> mmlog.txt
./m.sh traverser_4 test_scope_test 2>> mmlog.txt
