#pragma once

#include <aji/lib/cl.h>
#include <aji/lib/cmdline.h>
#include <aji/lib/cstring.h>
#include <aji/lib/cstring_vector.h>
#include <aji/lib/dict.h>
#include <aji/lib/error.h>
#include <aji/lib/file.h>
#include <aji/lib/format.h>
#include <aji/lib/memory.h>
#include <aji/lib/path.h>
#include <aji/lib/pipe.h>
#include <aji/lib/string.h>
#include <aji/lib/term.h>
#include <aji/lib/unicode.h>
#include <aji/lib/unicode_vector.h>
#include <aji/lib/unicode_path.h>
#include <aji/lib/void_vector.h>
#include <aji/lib/void_dict.h>
#include <aji/lib/socket.h>

#include <aji/core/args.h>
#include <aji/core/config.h>
#include <aji/core/constant.h>
#include <aji/core/error_stack.h>
#include <aji/core/types.h>
#include <aji/core/util.h>

#include <aji/lang/arguments.h>
#include <aji/lang/ast.h>
#include <aji/lang/chain_node.h>
#include <aji/lang/chain_nodes.h>
#include <aji/lang/chain_object.h>
#include <aji/lang/chain_objects.h>
#include <aji/lang/compiler.h>
#include <aji/lang/lex_env.h>
#include <aji/lang/excepts.h>
#include <aji/lang/gc.h>
#include <aji/lang/global.h>
#include <aji/lang/importer.h>
#include <aji/lang/kit.h>
#include <aji/lang/nodes.h>
#include <aji/lang/node_vector.h>
#include <aji/lang/node_dict.h>
#include <aji/lang/object.h>
#include <aji/lang/object_vector.h>
#include <aji/lang/object_dict.h>
#include <aji/lang/opts.h>
#include <aji/lang/scope.h>
#include <aji/lang/tokenizer.h>
#include <aji/lang/tokens.h>
#include <aji/lang/traverser.h>
#include <aji/lang/types.h>
#include <aji/lang/utils.h>

#include <aji/lang/builtin/functions.h>
#include <aji/lang/builtin/func_info.h>
#include <aji/lang/builtin/func_info_vector.h>
#include <aji/lang/builtin/module.h>

#include <aji/lang/builtin/modules/alias.h>
#include <aji/lang/builtin/modules/vector.h>
#include <aji/lang/builtin/modules/dict.h>
#include <aji/lang/builtin/modules/file.h>
#include <aji/lang/builtin/modules/opts.h>
#include <aji/lang/builtin/modules/unicode.h>
